/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gamebingo;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author TRAN HUY
 */
public class ClientBingo1 extends javax.swing.JFrame {
    
    String id;
    String clientID = "";
    static DataInputStream datain;
    static DataOutputStream dataout;
    DefaultListModel dlm;
    
    
    public static List<JButton> lBT;
    static BingoCard card = new BingoCard();
    static Socket sk;
    static int[] rows = new int[5];
    static int[] cols = new int[5];
    static int mainCross = 0;
    static int otherCross = 0;
    static boolean[][] status = new boolean[5][5];
    

    private static void fillCard(String msgin) {
        boolean check = false;
        int x = Integer.parseInt(msgin);
        
        int[][] cn = card.getCardNumber();
        for(int i = 0; i<5; i++){
            for(int j = 0; j < 5;j++){
                if(cn[i][j]==x){
                    check = true;
                    status[i][j] = true;
                    rows[i]++;
                    cols[j]++;
                    if(i==j) mainCross++;
                    if(i+j == 4) otherCross++;
                    break;
                }
            }
            if(check) break;
        }
    }
    /**
     * Creates new form ClientBingo1
     */
    public ClientBingo1() {
        initComponents();
        card.newCard(jpn_card);
    }

    ClientBingo1(String i, Socket s)
    {
        id = i;
        try {
            initComponents();
            lb_userID.setText("PLAYER: " + i);
            datain = new DataInputStream(s.getInputStream());
            dataout = new DataOutputStream(s.getOutputStream());
            new Read().start();
            card.newCard(jpn_card);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }

    class Read extends Thread
    {
        @Override
        public void run()
        {
            while (true) 
            {
                try
                {
                String datainClient = datain.readUTF();
                if (datainClient.contains(":;.,/=")) {
                        datainClient = datainClient.substring(6);
                        dlm.clear();
                        StringTokenizer st = new StringTokenizer(datainClient, ",");
                        while (st.hasMoreTokens()) {
                            String u = st.nextToken();
                            if (!id.equals(u)) {
                                dlm.addElement(u);
                            }
                        }
                    } else {
                        txt_area.append("" + datainClient + "\n");
                    }
                }
                catch (Exception ex)
                {
                    ex.printStackTrace();
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_userID = new javax.swing.JLabel();
        jpn_card = new javax.swing.JPanel();
        btn_bingo = new javax.swing.JButton();
        jNum = new javax.swing.JLabel();
        txt_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("i");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(414, 485));
        setMinimumSize(new java.awt.Dimension(414, 485));
        setResizable(false);
        setSize(new java.awt.Dimension(414, 485));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        lb_userID.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lb_userID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_userID.setText("BINGO: PLAYER 1");

        jpn_card.setLayout(new java.awt.GridLayout(5, 5));

        btn_bingo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn_bingo.setText("BINGO");
        btn_bingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bingoActionPerformed(evt);
            }
        });

        jNum.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNum.setText("số");
        jNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        txt_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fieldActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpn_card, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNum, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bingo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_userID)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jNum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bingo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpn_card, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        try
        {
            String m = txt_field.getText(),mm=m;
            String CI = clientID;
            if(!clientID.isEmpty())
            {
                m = "#4344554@@@@@67667@@";
                dataout.writeUTF(m);
                txt_field.setText("");
                txt_area.append("<you send to " + CI + ">" + mm + "\n");
            }
            else
            {
                dataout.writeUTF(m);
                txt_field.setText("");
                txt_area.append("<" +id+">" + " : "+ mm + "\n");
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this,"User does not exist");
        }
    }//GEN-LAST:event_btn_sendActionPerformed

    private void txt_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fieldActionPerformed

    private void btn_bingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bingoActionPerformed
        boolean check = bingoCheck();
        if(check) txt_field.setText("win");
        else changeButton();
    }//GEN-LAST:event_btn_bingoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientBingo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientBingo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientBingo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientBingo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ClientBingo1().setVisible(true);

            }
        });
        try
            {
                sk = new Socket("127.0.0.1",8080);
                
                String msgin = "";
                while (!msgin.equals("exit"))
                {
                    msgin = datain.readUTF();
                    fillCard(msgin);
                    jNum.setText(msgin); //hiện dữ liệu từ client lên msg_area
                }
            
            }
        catch (IOException e){}
        lBT = card.getCard();
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bingo;
    private static javax.swing.JButton btn_send;
    public static javax.swing.JLabel jNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JPanel jpn_card;
    private javax.swing.JLabel lb_userID;
    private static javax.swing.JTextArea txt_area;
    private static javax.swing.JTextField txt_field;
    // End of variables declaration//GEN-END:variables

    private boolean bingoCheck() {
        for(int i = 0;i<5;i++){
            if(rows[i]==5||cols[i]==5){
                return true;
            }
            
        }
        if (mainCross==5||otherCross==5) return true;
        return false;
    }

    private void changeButton() {
        List<JButton> jb = card.getCard();
        for(int i=0;i<25;i++){
            JButton btn = jb.get(i);
            if(btn.getBackground().equals(new java.awt.Color(0, 0, 0))&&!status[i/5][i%5]){
                btn.setBackground(new java.awt.Color(255,255,255));
                btn.setForeground(new java.awt.Color(0,0,0));
            }
        }
    }
}
